import { describe, expect, it } from 'vitest'

import { formatTokenFiles } from '../../../emitters/generate/format/formatTokenFiles.ts'
import type { TokenGroupData } from '../../../emitters/extract/assemblers/assembleTokenData.ts'

function createTokenGroup(
  overrides: Partial<TokenGroupData> = {},
): TokenGroupData {
  return {
    groupPath: '/tokens/button',
    name: 'button',
    styleName: 'buttonStyle',
    typeName: 'ButtonStyle',
    outputFile: '/generated/tokenModules/button.token.ts',
    tokens: [
      {
        infix: 'button',
        variables: [
          {
            key: 'bg',
            cssName: 'back-ground',
            allowed: ['f'],
            values: {},
          },
          {
            key: 'color',
            cssName: 'color',
            allowed: ['p', 'f'],
            values: {},
          },
        ],
      },
    ],
    ...overrides,
  }
}


describe('[EMITTER]', () => {
  describe('formatTokenFiles', () => {
    it('returns no files when there is no token data', () => {
      expect(formatTokenFiles([])).toEqual([])
    })

    it('formats a token file', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.outputFile).toBe(
        '/generated/tokenModules/button.token.ts',
      )

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by design-tokens-plugin.',
      )

      expect(result.content).toContain(
        'import type {',
      )

      expect(result.content).toContain(
        'StyleFromComponent,',
      )

      expect(result.content).toContain(
        'TokenComponent',
      )

      expect(result.content).toContain(
        'from "@shared/tokenUtils/compiler.types.ts"',
      )
    })

    it('emits the component name and generated style name', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'export const buttonStyle = {',
      )

      expect(result.content).toContain(
        'component: "button",',
      )
    })

    it('emits token variables using their keys and names', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'bg: { name: "back-ground", allowed: ["f"]}',
      )

      expect(result.content).toContain(
        'color: { name: "color", allowed: ["p","f"]}',
      )
    })

    it('emits the token infix as the token property', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'button: {',
      )
    })

    it('emits multiple tokens', () => {
      const [result] = formatTokenFiles([
        createTokenGroup({
          tokens: [
            {
              infix: 'button',
              variables: [
                {
                  key: 'bg',
                  cssName: 'back-ground',
                  allowed: ['f'],
                  values: {},
                },
              ],
            },
            {
              infix: 'hover',
              variables: [
                {
                  key: 'bg',
                  cssName: 'back-ground',
                  allowed: ['s', 'f'],
                  values: {},
                },
              ],
            },
          ],
        }),
      ])

      expect(result.content).toContain(
        'button: {',
      )

      expect(result.content).toContain(
        'hover: {',
      )

      expect(result.content).toContain(
        'bg: { name: "back-ground", allowed: ["s","f"]}',
      )
    })

    it('emits the generated type', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'export type ButtonStyle = StyleFromComponent<typeof buttonStyle>;',
      )
    })

    it('emits empty token collections', () => {
      const [result] = formatTokenFiles([
        createTokenGroup({
          tokens: [],
        }),
      ])

      expect(result.content).toContain(
        'export const buttonStyle = {',
      )

      expect(result.content).toContain(
        'vars: {',
      )
    })

    it('creates one file for each token group', () => {
      const results = formatTokenFiles([
        createTokenGroup(),
        createTokenGroup({
          name: 'surface',
          styleName: 'surfaceStyle',
          typeName: 'SurfaceStyle',
          outputFile: '/generated/tokenModules/surface.token.ts',
        }),
      ])

      expect(results).toHaveLength(2)

      expect(results.map(result => result.outputFile)).toEqual([
        '/generated/tokenModules/button.token.ts',
        '/generated/tokenModules/surface.token.ts',
      ])
    })
  })
})