import { describe, expect, it } from 'vitest'

import { formatPresetFiles } from '../../../emitters/generate/format/formatPresetFiles.ts'
import type { PresetFileData } from '../../../emitters/extract/assemblers/assemblePresetData.ts'

function createPreset(
  overrides: Partial<PresetFileData> = {},
): PresetFileData {
  return {
    presetName: 'buttonPreset',
    typeName: 'ButtonPreset',
    cssImport: '../../../components/Button/Button.module.css',
    outputFile: '/generated/presets/button.preset.ts',
    selectors: [
      'button',
      'active',
      'disabled',
    ],
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatPresetFiles', () => {
    it('returns no files when there is no preset data', () => {
      expect(formatPresetFiles([])).toEqual([])
    })

    it('forwards the output file path', () => {
      const [result] = formatPresetFiles([
        createPreset(),
      ])

      expect(result.outputFile).toBe(
        '/generated/presets/button.preset.ts',
      )
    })

    it('formats a preset file', () => {
      const [result] = formatPresetFiles([
        createPreset(),
      ])

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by design-tokens-plugin.',
      )

      expect(result.content).toContain(
        'import css from "../../../components/Button/Button.module.css";',
      )

      expect(result.content).toContain(
        'export const buttonPreset = {',
      )

      expect(result.content).toContain(
        'export type ButtonPreset = keyof typeof buttonPreset;',
      )
    })

    it('emits selectors as CSS module references', () => {
      const [result] = formatPresetFiles([
        createPreset({
          selectors: ['button', 'active'],
        }),
      ])

      expect(result.content).toContain(
        '  active: css.active,',
      )

      expect(result.content).toContain(
        '  button: css.button,',
      )
    })

    it('sorts selectors before emitting them', () => {
      const [result] = formatPresetFiles([
        createPreset({
          selectors: [
            'surface',
            'button',
            'active',
            'disabled',
          ],
        }),
      ])

      const active = result.content.indexOf('  active: css.active,')
      const button = result.content.indexOf('  button: css.button,')
      const disabled = result.content.indexOf('  disabled: css.disabled,')
      const surface = result.content.indexOf('  surface: css.surface,')

      expect(active).toBeLessThan(button)
      expect(button).toBeLessThan(disabled)
      expect(disabled).toBeLessThan(surface)
    })

    it('creates one file for each preset', () => {
      const results = formatPresetFiles([
        createPreset({
          presetName: 'buttonPreset',
          typeName: 'ButtonPreset',
          outputFile: '/generated/presets/button.preset.ts',
        }),
        createPreset({
          presetName: 'surfacePreset',
          typeName: 'SurfacePreset',
          outputFile: '/generated/presets/surface.preset.ts',
        }),
      ])

      expect(results).toHaveLength(2)

      expect(results.map(result => result.outputFile)).toEqual([
        '/generated/presets/button.preset.ts',
        '/generated/presets/surface.preset.ts',
      ])
    })
  })
})