import { describe, expect, it } from 'vitest'

import { formatExtensionFile } from '../../../emitters/generate/format/formatExtensionFile.ts'
import type { ExtensionData } from '../../../emitters/extract/assemblers/assembleExtensionData.ts'

function createExtensionData(
  overrides: Partial<ExtensionData> = {},
): ExtensionData {
  return {
    variables: [
      '--button-color',
      '--button-radius',
    ],
    outputFile:
      '/generated/metadata/extension.generated.jsonc',
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatExtensionFile', () => {
    it('returns the generated extension file path', () => {
      const data = createExtensionData()

      const result = formatExtensionFile(data)

      expect(result.outputFile)
        .toBe(data.outputFile)
    })

    it('emits the generated file header', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by design-tokens-plugin.',
      )
    })

    it('emits variables as a JSONC array', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.content).toContain(
        '"--button-color"',
      )

      expect(result.content).toContain(
        '"--button-radius"',
      )
    })

    it('separates multiple variables with commas', () => {
      const result = formatExtensionFile(
        createExtensionData({
          variables: [
            '--button-color',
            '--button-radius',
            '--button-size',
          ],
        }),
      )

      expect(result.content).toContain(
        '"--button-color",\n',
      )

      expect(result.content).toContain(
        '"--button-radius",\n',
      )

      expect(result.content).toContain(
        '"--button-size"',
      )
    })

    it('emits an empty array when there are no variables', () => {
      const result = formatExtensionFile(
        createExtensionData({
          variables: [],
        }),
      )

      expect(result.content).toContain(
        '[',
      )

      expect(result.content).toContain(
        ']',
      )

      expect(result.content).not.toContain(
        '"--',
      )
    })
  })
})