# ==================== SETTINGS ====================

set shell := ["bash", "-c"]

workspace := "ad-web-launcher.code-workspace"

# ================== DEFAULT ====================

default: help

# ================== DEVELOPMENT ====================

audit:
    npm audit

audit-all:
    ./scripts/run-cmd.sh audit

outdated:
    npm outdated

outdated-all:
    ./scripts/run-cmd.sh outdated || true

doctor:
    npm doctor

doctor-all:
    ./scripts/run-cmd.sh doctor

install:
    npm install

install-all:
    ./scripts/run-cmd.sh install
    ./scripts/run-cmd.sh install-scripts ls

update-all:
    ./scripts/run-cmd.sh update
    ./scripts/run-cmd.sh install-scripts ls

install-force +packages:
    ./scripts/install-force.sh {{ packages }}

dev:
    npm run dev

preview:
    npm run preview

build:
    npm run build && ./scripts/deploy-android.sh

# ==================== QUALITY ====================

type:
    npm run type

type-all: 
    ./scripts/run-script.sh type

test project="" *args:
    if [ -z "{{project}}" ]; then \
        npm run test -- --project=react --project=app --silent {{args}}; \
    else \
        npm run test -- --project={{project}} --silent {{args}}; \
    fi

test-all *args:
    npm run test -- --config=vitest.coverage.config.ts --silent=passed-only --reporter=dot {{args}}

# List available Vitest projects.
test-help:
    ./scripts/test-project.sh

coverage project="" *args:
    if [ -z "{{project}}" ]; then \
        npm run test -- --project=react --project=app --silent=passed-only --coverage {{args}}; \
    else \
        npm run test -- --project={{project}} --silent=passed-only --coverage {{args}}; \
    fi

coverage-all:
    just test-all --coverage

coverage-open:
    xdg-open coverage/index.html

lint *args:
    if [ -z "{{ args }}" ]; then \
        npm run lint; \
    else \
        ./scripts/lint.sh {{ args }}; \
    fi

stylelint *args:
    if [ -z "{{ args }}" ]; then \
        npm run stylelint; \
    else \
        npx stylelint {{ args }}; \
    fi

eslint *args:
    npx eslint {{ args }}

oxlint *args:
    npx oxlint {{ args }}

style: stylelint

ox: oxlint

es: eslint

knip *args:
    npm run knip -- {{ args }}

knip-all *args:
    ./scripts/knip-all.sh {{ args }}

# chmod +x scripts/index.sh <- an example for enabling a script

# ==================== EXTENSIONS ====================

# Builds and installs css-variable-completion (includes css-lsp helper).
install-cvc:
    cd tools/extensions/css-variable-completion && npm run package
    code --install-extension tools/extensions/css-variable-completion/css-variable-completion-0.0.1.vsix --force

# Builds and installs lint-on-start.
install-los:
    cd tools/extensions/lint-on-start && npm run package
    code --install-extension tools/extensions/lint-on-start/lint-on-start-0.0.1.vsix --force

# Builds compiler and installs the compiler extension.
install-tokens:
    cd tools/token-compiler && npm run build
    cd tools/extensions/token-compiler-vscode && npm run package
    code --install-extension tools/extensions/token-compiler-vscode/token-compiler-vscode-0.0.1.vsix --force

# Builds and installs all tools.
install-extensions: install-cvc install-los install-tokens

# Runs the compiler in CLI. File emissions disabled.
compiler:
    cd tools/token-compiler && npm run cli -- exe ../..

# ==================== WORKSPACE ====================

open:
    @echo "🤖 Opening workspace from WSL..."
    code {{ workspace }}

open-new:
    @echo "🤖 Opening workspace in a new window..."
    code -n {{ workspace }}

# ==================== DELETABLES ====================

# Check whether the current TypeScript version is supported by typescript-eslint
check-ts-v:
    npm view typescript-eslint@latest peerDependencies
    npm view @typescript-eslint/parser@latest peerDependencies

# Lists the dependencies of project versus tools. Takes dependency as args.
check-deps *args:
    scripts/dependencies.sh {{ args }}

    
# ==================== HELP ====================

help:
    @echo ""
    @echo "==================== COMMAND SURFACE ===================="
    @echo ""
    @echo "[JUST] orchestration layer"
    @echo "→ just"
    @just --list
    @echo ""
    @echo "[NPM] package scripts"
    @echo "→ npm run"
    @npm pkg get scripts
